version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: paste_user
      POSTGRES_PASSWORD: paste_password
      POSTGRES_DB: pastebin_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paste_user -d pastebin_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Основной API сервис
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://paste_user:paste_password@db:5432/pastebin_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pasted_texts:/app/pasted_texts

  # Контейнер-дворник (Cleanup Worker)
  cleanup_worker:
    build: .
    # Маленькая хитрость: запускаем скрипт в бесконечном цикле каждые 10 минут
    command: >
      sh -c "while true; do python cleanup/cleanup.py; sleep 600; done"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://paste_user:paste_password@db:5432/pastebin_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pasted_texts:/app/pasted_texts
